language: php
php:
  - 5.4
  
before_script:
  - composer install --dev --no-interaction
  
script:
  - phpunit -c tests --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover